version: '3.8'

services:
  app:
    build: .
    container_name: barbearia_app
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - evolution_api
    networks:
      - barbearia_net

  db:
    image: postgres:15-alpine
    container_name: barbearia_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_DB=barbearia_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - barbearia_net

  evolution_api:
    image: evoapicloud/evolution-api:v1.8.0
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_URL=http://104.197.162.83:8080
      - DATABASE_PROVIDER=sqlite
      - AUTHENTICATION_API_KEY=iOS8d66fEr6Ou2M8nhJZRz6SKAmOGQkF
      - DISABLE_MANAGER=false
    volumes:
      - evolution_data:/store
    networks:
      - barbearia_net

volumes:
  pg_data:
  evolution_data:

networks:
  barbearia_net:
